completed assignment
learn-academy-2021-bravo/week-4-assessment-JJSanch pull request #1
Opened 2021-06-01 15:49 UTC by JJSanch

2021-06-01 16:22 UTC, WalkerTexas-coder requested changes
Good stuff, I want to see a couple changes before I approve.

2021-06-01 16:22 UTC, WalkerTexas-coder commented on code_challenges.rb
> +#Here I knew to create a new method but did not know how to apply the delete method to get expected output
No worries, What are the logical movement you would make (dont worry about syntax) to make this happen? 
ex. Step 1.) take in string 2.)split string 3.) ... so on and so fourth

2021-06-01 16:22 UTC, WalkerTexas-coder commented on code-challenges.test.js
> +    else if(array === [109, 5, 9, -59, 8, 24]) {
Here we could just use an "else" and that would get us headed in the right direction.

2021-06-01 16:22 UTC, WalkerTexas-coder commented on code_challenges.rb
> +#Here I could not figure out how to get desired output or print it without getting an error
in your initialize you are passing three parameters. when you instantiate the new bike 
```
 trek_bike = Bike.new (argument1, argument2 , argument3)
p trek_bike.info
```
try to implement this kind of code and tell me what you get!

2021-06-01 16:22 UTC, WalkerTexas-coder commented on interview-questions.md
> +  Your answer: A block is a portion of code
Good, but in the future elaborate on your answers. Try to hit the big 6 questions Who? What? When? Where? why? how?

2021-07-02 15:17 UTC, JJSanch commented on code-challenges.test.js
> +    else if(array === [109, 5, 9, -59, 8, 24]) {
Got it.

What would I put in the last else statement?

2021-07-02 15:33 UTC, JJSanch commented on code_challenges.rb
> +#Here I could not figure out how to get desired output or print it without getting an error
I understand that this code would then return a new trek_bike with the new arguments, but I could not get it to show up in the console.

2021-07-02 15:43 UTC, JJSanch commented on interview-questions.md
> +  Your answer: A block is a portion of code
Understood

2021-07-06 01:18 UTC, merged